run:
  timeout: 30s
  tests: true
  allow-parallel-runners: true
issues:
  exclude:
    - abcdef
exclude-use-default: false
linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - varcheck
    - whitespace
    - asciicheck
    - godox
    - maligned
    - prealloc
    - golint
#    - unparam
#    - stylecheck
#    - nestif
#    - goerr113
#    - gomnd
#    - unused
#    - testpackage
#    - deadcode
#    - wsl
#    - gochecknoglobals
#    - gocognit
#    - godot
#    - funlen
#    - gochecknoinits

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - captLocal
      - appendAssign
  lll:
    line-length: 150
  golint:
    min-confidence: 0.8